### ISSUE TITLE
[아이템 02] 생성자에 매개변수가 많다면 빌더를 고려하라

### ISSUE THREAD

**Issue by ghojeong** [study-records/effective-java#2]

**Comment by punsoo** [comment]
p16에 일관성(consistency)에 대해서 완벽히 이해하지 못한거 같습니다
특히 

> 일관성이 깨진 객체가 만들어지면, 버그를 심은 코드와 그 버그 때문에 런타임에 문제를 겪는 코드가 물리적으로 멀리 떨어져 있을 것이므로 디버깅도 만만치 않다.

이 인용절에서 물리적으로 멀리 떨어져 있다는 것은 무슨 말일까요?

**Comment by ghojeong** [comment]
> 일관성(consistency)에 대해서 완벽히 이해하지 못한거 같습니다 

일관성이 깨졌다는 것은 여러가지 의미로 사용될 수 있는 말이지만,
여기서는 "완전히 생성되기 전"의 초기화가 덜 된 상태를 의미합니다.
사용자가 정말 실수로라도 생성되기전의 객체를 사용해버려서, 런타임 에러가 발생할 수도 있는 위험성이 있는 것이지요.

**Comment by ghojeong** [comment]
> 물리적으로 멀리 떨어져 있다는 것은 무슨 말일까요?

여기서 물리적으로 떨어진 두 대상은 "버그의 원인이 되는 코드"와 "버그가 발생한 코드"의 위치입니다.
일관성과 관련된 상황에서 버그가 발생한 근본적인 원인은 결국, 객체의 초기화가 불완전하기 때문입니다.
하지만 런타임 에러 코드가 발생되는 코드는 초기화를 하는 코드부분이 아니라,
불완전한 객체를 넘겨받아서 그 객체를 구동하는 코드입니다.

이 둘의 코드는 전혀 다른 클래스, 혹은 심지어 전혀 다른 패키지 일 수도 있으므로 코드가 물리적으로 멀리 떨어져 있다고 하는 것입니다.

**Comment by punsoo** [comment]
객체를 초기화하는 부분과 넘겨받아 사용하는 코드가 구분된다는 뜻이군요 답변 감사합니다
