### ISSUE TITLE
[아이템 04] 인스턴스화를 막으려거든 private 생성자를 사용하라

### ISSUE THREAD

**Issue by ghojeong** [study-records/effective-java#4]

**Comment by punsoo** [comment]
p26에 보면

> 마지막으로, final  클래스와 관련한 메서드들을 모아놓을 때도 사용한다. final 클래스를 상속해서 하위 클래스에 메서드를 넣는 건 불가능하기 때문이다.

라고 되어있는데요, final 클래스 관련한 메서드들을 정적 유틸리티 클래스를 이용해 모아둔다는 거 같습니다
그렇다면, 일반적인 클래스 A가 있을 때 A와 관련된 메소드들은 A를 상속한 B클래스에 넣어두나요 보통?

**Comment by ghojeong** [comment]
**Lastly, such classes can be used to group methods on a final class, since you can’t put them in a subclass.**

만약 의미가 헷갈린다 싶으면 영어 원문을 찾아보도록 합시다.
위의 문장에서 말하는 "such classes" 란 `a class that is just a grouping of static methods and static fields` 입니다.
한국말로 하자면
(1.) 생성자가 final 이고, (2.) 메소드와 멤버가 모두 static 인 클래스가 되겠네요.

final 클래스가 대체 뭐하는 클래스이지?  하고 찾아보니깐 영어 원문에는 그런 워딩이 존재하지 조차 않네요...
번역이 오해를 부르게끔 괴상하게 되어 있는 것 같습니다.

> 일반적인 클래스 A가 있을 때 A와 관련된 메소드들은 A를 상속한 B클래스에 넣어두나요 보통?

오해를 하신것 같습니다. 말씀주신 문장은 상속관계랑은 별 관련이 없습니다.
그냥 final 생성자로 선언한 클래스는 상속이 불가능하니깐,
(extends 문법은 사용 가능해도 자식 클래스 인스턴스가 생성이 불가능해서 상속이 불가능하다고 봐야합니다.)

A 부모 클래스의 메소드를 B 자식 클래스에 넣는 괴상한 짓은 하지 마시고,
그냥 상속이 불가능한 상황에서는 A 에 정의된 로직들을 B 와 같은 다른 클래스에서 재사용이 불가능하니깐,
차라리 인스턴스 생성 없이도 재사용할 수 있게끔 static 으로 선언하라는 의미로 받아들이시면 될것 같습니다.

**Comment by punsoo** [comment]
답변 감사합니다 😁
