### ISSUE TITLE
[아이템 06] 불필요한 객체 생성을 피하라

### ISSUE THREAD

**Issue by ghojeong** [study-records/effective-java#6]

**Comment by punsoo** [comment]
p32 에 유한 상태 머신이란 무엇일까요?

**Comment by punsoo** [comment]
p33에

> 반혼된 Set 인스턴스가 일반적으로 가변이더라도 반환된 인스턴스들은 기능적으로 모두 똑같다

이 부분이 정확 히 무슨 의미일까요?

앞뒤 문맥에서 map의 keySet 메서드로 똑같은 인스턴스의 Set이 반환되는 건 알겠는데

저 문장은 조금 헷갈리네요

**Comment by ghojeong** [comment]
> p32 에 유한 상태 머신이란 무엇일까요?

[유한 상태 머신(FSM)](https://en.wikipedia.org/wiki/Finite-state_machine) 은 오토마타를 뜻합니다. 컴공 전공 필수 과목 중에 계산 이론을 듣게 되면 질리도록 배울 수 있습니다.

**Comment by ghojeong** [comment]
FSM 이 무엇인지 공부하는 것 보다는 정규표현식을 자바에서 사용하려고 하면,
정규표현식보다 객체가 별도로 생성되는 오버헤드가 발생한다는 점을 더 주의 깊게 기억하고 가면 될 것 같아요.
즉 문자열 가공을 할 때 정규표현식을 활용하려하는건, 다른언어와 다르게 자바에서는 그다지 권장되는 방법이 아니라는 것이죠.

**Comment by ghojeong** [comment]
> 반환된 Set 인스턴스가 일반적으로 가변이더라도 반환된 인스턴스들은 기능적으로 모두 똑같다

한국어 번역이 잘 이해가 가지 않을 때는 영어 원문을 찾아서 읽어보도록 합시다.

"Although the returned Set instance is typically mutable, all of the returned objects are functionally identical: 
when one of the returned objects changes, so do all the others, because they’re all backed by the same Map instance. "

**Comment by ghojeong** [comment]
마치 Set 인스턴스가 mutable 하기 때문에 방어적 복사로 구현이 되었다면, 별개의 인스턴스가 매번 생성되는게 아닌가 생각할 수도 있지만,

데이터 정합성 때문에 반환된 Set 인스턴스가 변환된다면 연관된 모든 자료구조도 변경되어야 하는게 맞기 때문에, 하나의 인스턴스로 연결되도록 구현되어 있다고 주장하는 것 같네요.

궁금하시면 keySet 으로 Set 인스턴스를 2개 받아와서, 한개가 수정되면 다른 한개도 수정되는 지 확인해보면 좋을 것 같아요.

**Comment by ghojeong** [comment]
아이템 6 읽은 소감과 제가 기억을 할 수 있을 것 같은 내용을 글로 정리해보았습니다.

https://www.notion.so/06-0a2fa0e0985f436cb1c602a388566f68

**Comment by punsoo** [comment]
그렇군요 답변 감사합니다! 저도 정리한 글이 있어요
https://punsoo.github.io/effective%20java/Effective-Java-Item-06/
